name: AWS ECS 배포
on:
  workflow_call:

jobs:
  deploy:
    runs-on: [ ubuntu-latest ]
    name: ECS 배포하기

    permissions:
      id-token: write
      contents: read

    steps:
      - name: AWS ECR 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
