name: 프로덕션 워크플로우
on:
  push:
    branches: [ 'main' ]

concurrency:
  group: api

jobs:
  call-build-workflow:
    name: 이미지 빌드
    uses: ./.github/workflows/build.yaml
    permissions:
      id-token: write
      contents: read
