name: 프로덕션 워크플로우
on:
  push:
    branches: [ 'main' ]
    paths:
      - 'src/**' # 어드민 API 코드가 변경된 경우
      - '.github/workflows/**' # 워크플로우와 관련된 파일이 변경된 경우
      - 'build.gradle.kts' # Parent Gradle 모듈 설정이 변경된 경우
      - 'settings.gradle' # Parent Gradle 설정이 변경된 경우

concurrency:
  group: api

jobs:
#  call-test-workflow:
#    name: 테스트 실행
#    uses: ./.github/workflows/test.yaml
#    permissions:
#      id-token: write
#      contents: read
  call-build-workflow:
    name: 이미지 빌드
    uses: ./.github/workflows/build.yaml
    permissions:
      id-token: write
      contents: read
