name: 테스트
on:
  workflow_call:

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: 이미지 빌드하기

    permissions:
      id-token: write
      contents: read

    steps:
      - name: GitHub 에서 레포 받아오기
        uses: actions/checkout@v3

      - name: JDK17 준비하기
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 준비하기
        uses: gradle/gradle-build-action@v2

      - name: 테스트 실행
        run: |
          chmod +x gradlew
          ./gradlew --info test

      - name: 테스트 결과 출력
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml

      - name: PR에 테스트 결과 업로드
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
